apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    imageregistry: "https://hub.docker.com"
    buildURL: "https://jenkins.com/expense/job/backend/23"
spec:
  containers:
  - name: nginx
    image: nginx