apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    component: backend
    tier: web
    purpose: practice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80