apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: frontend
    tier: web 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend 
      tier: web 
  template:
    metadata:
      labels:
        app: frontend 
        tier: web 
    spec:
      containers:
      - name: nginx
        image: koti0120/demo-deployment:1.0.0